/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table index_entries
	 */
	public static final io.corps.sgoc.jooq.tables.IndexEntries INDEX_ENTRIES = io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES;

	/**
	 * The table log_entries
	 */
	public static final io.corps.sgoc.jooq.tables.LogEntries LOG_ENTRIES = io.corps.sgoc.jooq.tables.LogEntries.LOG_ENTRIES;

	/**
	 * The table objects
	 */
	public static final io.corps.sgoc.jooq.tables.Objects OBJECTS = io.corps.sgoc.jooq.tables.Objects.OBJECTS;
}
