/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogEntriesRecord extends org.jooq.impl.UpdatableRecordImpl<io.corps.sgoc.schema.tables.records.LogEntriesRecord> implements org.jooq.Record3<java.lang.String, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1472733130;

	/**
	 * Setter for <code>sgoc_test.log_entries.root_key</code>.
	 */
	public void setRootKey(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sgoc_test.log_entries.root_key</code>.
	 */
	public java.lang.String getRootKey() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sgoc_test.log_entries.sequence</code>.
	 */
	public void setSequence(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sgoc_test.log_entries.sequence</code>.
	 */
	public java.lang.Long getSequence() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>sgoc_test.log_entries.timestamp</code>.
	 */
	public void setTimestamp(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sgoc_test.log_entries.timestamp</code>.
	 */
	public java.lang.Long getTimestamp() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.ROOT_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.SEQUENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getRootKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSequence();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getTimestamp();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LogEntriesRecord
	 */
	public LogEntriesRecord() {
		super(io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES);
	}

	/**
	 * Create a detached, initialised LogEntriesRecord
	 */
	public LogEntriesRecord(java.lang.String rootKey, java.lang.Long sequence, java.lang.Long timestamp) {
		super(io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES);

		setValue(0, rootKey);
		setValue(1, sequence);
		setValue(2, timestamp);
	}
}
