/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.schema.tables.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjectsRecord extends org.jooq.impl.UpdatableRecordImpl<io.corps.sgoc.schema.tables.tables.records.ObjectsRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, byte[], java.lang.Long> {

	private static final long serialVersionUID = 1377597194;

	/**
	 * Setter for <code>sgoc_test.objects.root_key</code>.
	 */
	public void setRootKey(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sgoc_test.objects.root_key</code>.
	 */
	public java.lang.String getRootKey() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sgoc_test.objects.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sgoc_test.objects.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sgoc_test.objects.object</code>.
	 */
	public void setObject(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sgoc_test.objects.object</code>.
	 */
	public byte[] getObject() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>sgoc_test.objects.timestamp</code>.
	 */
	public void setTimestamp(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sgoc_test.objects.timestamp</code>.
	 */
	public java.lang.Long getTimestamp() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, byte[], java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, byte[], java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return io.corps.sgoc.schema.tables.tables.Objects.OBJECTS.ROOT_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return io.corps.sgoc.schema.tables.tables.Objects.OBJECTS.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field3() {
		return io.corps.sgoc.schema.tables.tables.Objects.OBJECTS.OBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return io.corps.sgoc.schema.tables.tables.Objects.OBJECTS.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getRootKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getObject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTimestamp();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ObjectsRecord
	 */
	public ObjectsRecord() {
		super(io.corps.sgoc.schema.tables.tables.Objects.OBJECTS);
	}

	/**
	 * Create a detached, initialised ObjectsRecord
	 */
	public ObjectsRecord(java.lang.String rootKey, java.lang.String uuid, byte[] object, java.lang.Long timestamp) {
		super(io.corps.sgoc.schema.tables.tables.Objects.OBJECTS);

		setValue(0, rootKey);
		setValue(1, uuid);
		setValue(2, object);
		setValue(3, timestamp);
	}
}
