/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.schema;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>sgoc_test</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.IndexEntriesRecord> KEY_INDEX_ENTRIES_PRIMARY = UniqueKeys0.KEY_INDEX_ENTRIES_PRIMARY;
	public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.LogEntriesRecord> KEY_LOG_ENTRIES_PRIMARY = UniqueKeys0.KEY_LOG_ENTRIES_PRIMARY;
	public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.LogEntriesRecord> KEY_LOG_ENTRIES_IDX_UNIQUE_USER_TOKEN_TIMESTAMP = UniqueKeys0.KEY_LOG_ENTRIES_IDX_UNIQUE_USER_TOKEN_TIMESTAMP;
	public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.ObjectsRecord> KEY_OBJECTS_PRIMARY = UniqueKeys0.KEY_OBJECTS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<io.corps.sgoc.schema.tables.records.IndexEntriesRecord, io.corps.sgoc.schema.tables.records.ObjectsRecord> INDEX_ENTRIES_IBFK_1 = ForeignKeys0.INDEX_ENTRIES_IBFK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.IndexEntriesRecord> KEY_INDEX_ENTRIES_PRIMARY = createUniqueKey(io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.ROOT_KEY, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.INDEX_KEY, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.INDEX_VALUE, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.UUID);
		public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.LogEntriesRecord> KEY_LOG_ENTRIES_PRIMARY = createUniqueKey(io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES, io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.ROOT_KEY, io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.SEQUENCE);
		public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.LogEntriesRecord> KEY_LOG_ENTRIES_IDX_UNIQUE_USER_TOKEN_TIMESTAMP = createUniqueKey(io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES, io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.ROOT_KEY, io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES.TIMESTAMP);
		public static final org.jooq.UniqueKey<io.corps.sgoc.schema.tables.records.ObjectsRecord> KEY_OBJECTS_PRIMARY = createUniqueKey(io.corps.sgoc.schema.tables.Objects.OBJECTS, io.corps.sgoc.schema.tables.Objects.OBJECTS.ROOT_KEY, io.corps.sgoc.schema.tables.Objects.OBJECTS.UUID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<io.corps.sgoc.schema.tables.records.IndexEntriesRecord, io.corps.sgoc.schema.tables.records.ObjectsRecord> INDEX_ENTRIES_IBFK_1 = createForeignKey(io.corps.sgoc.schema.Keys.KEY_OBJECTS_PRIMARY, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.ROOT_KEY, io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES.UUID);
	}
}
