/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SgocTest extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1966012869;

	/**
	 * The singleton instance of <code>sgoc_test</code>
	 */
	public static final SgocTest SGOC_TEST = new SgocTest();

	/**
	 * No further instances allowed
	 */
	private SgocTest() {
		super("sgoc_test");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES,
			io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES,
			io.corps.sgoc.schema.tables.Objects.OBJECTS);
	}
}
