/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in sgoc_test
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sgoc_test.index_entries
	 */
	public static final io.corps.sgoc.schema.tables.IndexEntries INDEX_ENTRIES = io.corps.sgoc.schema.tables.IndexEntries.INDEX_ENTRIES;

	/**
	 * The table sgoc_test.log_entries
	 */
	public static final io.corps.sgoc.schema.tables.LogEntries LOG_ENTRIES = io.corps.sgoc.schema.tables.LogEntries.LOG_ENTRIES;

	/**
	 * The table sgoc_test.objects
	 */
	public static final io.corps.sgoc.schema.tables.Objects OBJECTS = io.corps.sgoc.schema.tables.Objects.OBJECTS;
}
