/**
 * This class is generated by jOOQ
 */
package io.corps.sgoc.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexEntriesRecord extends org.jooq.impl.UpdatableRecordImpl<io.corps.sgoc.jooq.tables.records.IndexEntriesRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, byte[], byte[]> {

	private static final long serialVersionUID = -669368460;

	/**
	 * Setter for <code>index_entries.root_key</code>.
	 */
	public void setRootKey(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>index_entries.root_key</code>.
	 */
	public java.lang.String getRootKey() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>index_entries.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>index_entries.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>index_entries.index_key</code>. binary of the proto
	 */
	public void setIndexKey(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>index_entries.index_key</code>. binary of the proto
	 */
	public byte[] getIndexKey() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>index_entries.index_value</code>. binary of the proto
	 */
	public void setIndexValue(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>index_entries.index_value</code>. binary of the proto
	 */
	public byte[] getIndexValue() {
		return (byte[]) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record4<java.lang.String, byte[], byte[], java.lang.String> key() {
		return (org.jooq.Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, byte[], byte[]> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, byte[], byte[]> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES.ROOT_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field3() {
		return io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES.INDEX_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES.INDEX_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getRootKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getIndexKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getIndexValue();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IndexEntriesRecord
	 */
	public IndexEntriesRecord() {
		super(io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES);
	}

	/**
	 * Create a detached, initialised IndexEntriesRecord
	 */
	public IndexEntriesRecord(java.lang.String rootKey, java.lang.String uuid, byte[] indexKey, byte[] indexValue) {
		super(io.corps.sgoc.jooq.tables.IndexEntries.INDEX_ENTRIES);

		setValue(0, rootKey);
		setValue(1, uuid);
		setValue(2, indexKey);
		setValue(3, indexValue);
	}
}
